### ISSUE TITLE
Moodle 3.3 compability?

### ISSUE THREAD

**Issue by Jarvil** [elearningsoftware/moodle-mod_journal#34]
Hello,

Will this plugin be Moodle 3.3 compatible?

**Comment by dmonllao** [comment]
Please @elearningsoftware you assumed this plugin maintenance and I don't see any update nor replies to people's queries since then. There is people like @danmarsden that are sending pull requests and people asking for the plugin compatibility with 3.3 in here and in https://moodle.org/plugins/mod_journal. There are many sites using this plugin, would be nice that you do actively maintain it or just let someone else do it.

**Comment by lucaboesch** [comment]
@mudrd8mz, @elearningsoftware, you are not even linking this correctly in https://moodle.org/plugins/mod_journal…

**Comment by watkec** [comment]
I have just sent messages to Herman Cosmin, Adrian Sarmas, and Ovidiu Morariu asking about this. Here is the message I sent:  Thanks for your work on the Journal plugin for Moodle. I noticed that the last build that was released is: Journal 31.0 (Build: 2016062800). With Moodle version 3.4 having just been released, I would like to know if you have a roadmap for updates to this plugin or is this plugin headed for deprecation. Thanks for your help.

I will let you know if I hear something back. Thanks.

**Comment by danmarsden** [comment]
I really think it's time for someone else to take on maintenance. They may have had good intentions but have not done any maintenance on this plugin  since officially taking over, despite receiving pull requests and previously promising to do something. Even if they do something now they have shown they don't care much about it and it would be better for the community for someone more active to pick it up.

**Comment by mudrd8mz** [comment]
We have a meeting scheduled with the current maintainers later this week to discuss the situation. Thanks everybody for your patience.

**Comment by adrian-sarmas** [comment]
We have released updated versions for Moodle 3.1 - 3.4 and will be working on maintaining this plugin. Sorry for the delay.
