### ISSUE TITLE
Deprecated function error on Totara 12

### ISSUE THREAD

**Issue by logan-reynolds** [elearningsoftware/moodle-mod_journal#41]
Saw this error when testing latest M33 version 2017121107 on Totara 12 within courses where a mod_journal instance is present - this is just a note in case T12-compatibility is considered to maintain this plugin's M3.3 branch:
```
The function journal_print_recent_activity have being deprected since totara 11

    line 234 of /blocks/recent_activity/block_recent_activity.php: call to debugging()
    line 74 of /blocks/recent_activity/block_recent_activity.php: call to block_recent_activity->get_modules_recent_activity()
    line 340 of /blocks/moodleblock.class.php: call to block_recent_activity->get_content()
    line 266 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
    line 1247 of /lib/blocklib.php: call to block_base->get_content_for_output()
    line 1302 of /lib/blocklib.php: call to block_manager->create_block_contents()
    line 281 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
    line 37 of /theme/basis/layout/partials/head.php: call to core_renderer->standard_head_html()
    line 39 of /theme/basis/layout/default.php: call to require()
    line 898 of /lib/outputrenderers.php: call to include()
    line 828 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 252 of /course/view.php: call to core_renderer->header()
```

**Comment by adrian-sarmas** [comment]
Thank you @logan-reynolds for reporting this issue and providing detailed information.

The function journal_print_recent_activity is not deprecated in Moodle, and the mod_journal plugin is actively maintained to support Moodle versions 3.9 through 4.5. It appears that this error is specific to Totara, as Totara has deprecated this function since version 11.

While the mod_journal plugin is designed for Moodle, Totara compatibility is not officially supported. That said, if Totara-specific changes are needed to resolve this issue, they would require separate consideration or contributions from the community.

If you encounter any issues while using the plugin in Moodle, please feel free to report them. However, for Totara-specific compatibility, you may need to adapt the code to address the deprecated function or seek support from the Totara community.

Thank you for your understanding!
