### ISSUE TITLE
Journal activity name appears twice in breadcrumbs

### ISSUE THREAD

**Issue by chiaravicere** [elearningsoftware/moodle-mod_journal#59]
This doesn't make any sense to me. It is confusing to have a second working link to the present page.

**Comment by argwallace** [comment]
This can be fixed by going into the file "view.php" and comment out line 57 so it looks like this:

// $PAGE->navbar->add($journalname);

**Comment by drachels** [comment]
I think this is actually a bug. Instead of listing the Journal name again, it should be using a language string that tells you what part of the Journal you are looking at. e.g. $PAGE->navbar->add(get_string("viewmyentries", "journal")); with an appropriate language string.
Same thing in the report.php page where you might use: $PAGE->navbar->add(get_string("gradeentries", "journal")); also with an appropriate language string.

**Comment by adrian-sarmas** [comment]
This has been fixed in the latest release.
