### ISSUE TITLE
Description is duplicated in Moodle 4.1

### ISSUE THREAD

**Issue by davefoord** [elearningsoftware/moodle-mod_journal#93]
In Moodle 4.1.1 the description of the Journal is being displayed twice, which looks odd and is confusing. I assume that this is a bug.

**Comment by andreasilvestriunitn** [comment]
We have Moodle 4.1.18 and Journal v4.5.0 ([Tag v1.32.0](https://github.com/elearningsoftware/moodle-mod_journal/releases/tag/v1.32.0)) and this issue persists.
Tried also in Moodle 4.5.0 and the issue is present.

We have temporarily resolved commenting three lines (66, 67, 68) in view.php:
`// if (!empty($journal->intro)) {
//     echo $OUTPUT->box(format_module_intro('journal', $journal, $cm->id), 'generalbox', 'intro');
// }`

But don't know if this is the right/best solution.

Thanks
